"use client";
import { useState } from "react";

type City={name:string;state:string;cost:number;work:string;business:string;vibe:string};
type Industry={name:string;icon:string;entry:number;income:number;skill:string;skillGain:number;description:string};
type Person={name:string;role:string;trust:number;friendship:number;known:boolean};
type Player={name:string;education:string;cash:number;energy:number;happiness:number;day:number;income:number;job:string;industry:string;home:string;rent:number;food:number;data:number;transport:number;skills:number;reputation:number;relationships:number;business:string|null;people:Person[];relationship:string|null;flags:string[];city:City;careerLevel:number;careerXp:number};
type Choice={label:string;result:string;cash?:number;energy?:number;happiness?:number;reputation?:number;trust?:number;flag?:string;skills?:number};
type Story={id:string;title:string;text:string;person?:string;choices:Choice[]};

const cities:City[]=[
{name:"Lagos",state:"Lagos",cost:1.2,work:"Tech, finance, media & trade",business:"Retail, food, logistics & digital services",vibe:"Fast, expensive, opportunity everywhere"},
{name:"Port Harcourt",state:"Rivers",cost:1,work:"Energy, services & trade",business:"Oil services, logistics, food & retail",vibe:"Business connections can move quickly"},
{name:"Abuja",state:"FCT",cost:1.15,work:"Government, consulting & services",business:"Professional services, hospitality & retail",vibe:"Connections and formal work matter"},
{name:"Ibadan",state:"Oyo",cost:.8,work:"Education, trade & services",business:"Food, retail, agriculture & services",vibe:"Lower costs and room to build"},
{name:"Kano",state:"Kano",cost:.75,work:"Trade, manufacturing & agriculture",business:"Wholesale, textiles, food & trade",vibe:"Trade networks are powerful"}];

const industries:Industry[]=[
{name:"Technology",icon:"💻",entry:0,income:32000,skill:"Digital skill",skillGain:4,description:"Software, support, product and digital work."},
{name:"Healthcare",icon:"💊",entry:15000,income:27000,skill:"Clinical skill",skillGain:4,description:"Pharmacy, clinics, health services and care."},
{name:"Oil & Gas",icon:"🛢️",entry:40000,income:45000,skill:"Technical skill",skillGain:5,description:"Energy services, field work and contracting."},
{name:"Agriculture",icon:"🌾",entry:10000,income:24000,skill:"Production skill",skillGain:5,description:"Farming, processing, distribution and agribusiness."},
{name:"Finance",icon:"💳",entry:20000,income:36000,skill:"Financial skill",skillGain:4,description:"Banking, accounting, fintech and financial services."},
{name:"Creative & Media",icon:"🎨",entry:5000,income:25000,skill:"Creative skill",skillGain:5,description:"Music, video, design, content and media."},
{name:"Trade & Retail",icon:"🛒",entry:0,income:22000,skill:"Sales skill",skillGain:4,description:"Buying, selling, distribution and retail."},
{name:"Entrepreneurship",icon:"🚀",entry:50000,income:0,skill:"Business skill",skillGain:6,description:"Build your own company instead of taking a salary."}];

const starts={Graduate:{cash:150000,job:"Unemployed",income:0,industry:"None"},Hustler:{cash:80000,job:"Freelancer",income:25000,industry:"Creative & Media"},"Family Support":{cash:200000,job:"Unemployed",income:0,industry:"None"},Entrepreneur:{cash:100000,job:"Founder",income:0,industry:"Entrepreneurship"}};
const homes=[["Family home",0],["Shared apartment",8500],["Self-contained",18000],["1-bedroom",30000]];
const events=[["Your data finished.","You buy another bundle.",-4500,0,-3],["A friend needs help.","You lend them ₦10,000.",-10000,0,5],["Transport fare increased.","Getting around costs more today.",-3000,-5,-2],["Small win!","A client sends you a surprise tip.",12000,0,8],["Power outage.","You spend on a quick alternative.",-3500,-2,-4],["Someone recommends you.","A new contact could become useful.",0,0,6]] as const;
const initialPeople:Person[]=[{name:"Tunde",role:"old friend",trust:62,friendship:58,known:true},{name:"Amaka",role:"former classmate",trust:55,friendship:48,known:true},{name:"Kunle",role:"business contact",trust:45,friendship:30,known:true},{name:"Aunty Bose",role:"family connection",trust:78,friendship:72,known:true}];
const stories:Story[]=[
{id:"tunde-business",title:"Tunde's Opportunity",text:"Tunde calls. “Omo, I get one small business opportunity. We fit make money, but I need ₦30,000 to start.”",person:"Tunde",choices:[{label:"Invest ₦30,000",result:"You send the money. Tunde promises to return your share after the first sales.",cash:-30000,trust:8,flag:"tunde-invested"},{label:"Ask for more details",result:"You ask questions before sending money. Tunde respects that.",trust:5,flag:"tunde-diligence"},{label:"Refuse politely",result:"You keep your cash. Tunde understands, but the opportunity passes.",happiness:-1,flag:"tunde-refused"}]},
{id:"amaka-job",title:"A Better Opportunity",text:"Amaka says her company is hiring. The role pays more, but you need to show up for an interview tomorrow.",person:"Amaka",choices:[{label:"Go for the interview",result:"You make the interview and improve your professional reputation.",energy:-8,reputation:8,skills:3,flag:"amaka-interview"},{label:"Ask her to recommend you",result:"Amaka puts your name forward. Your network gets stronger.",reputation:5,trust:8,flag:"amaka-referred"},{label:"Ignore it",result:"You stay with your current routine.",flag:"amaka-ignored"}]},
{id:"kunle-scam",title:"Quick Money",text:"Kunle sends a message: “Omo, guaranteed profit. Just send ₦20k now.” Something about the pitch feels rushed.",person:"Kunle",choices:[{label:"Send ₦20,000",result:"You take the gamble. Kunle disappears for a few days.",cash:-20000,trust:-20,happiness:-8,flag:"kunle-gamble"},{label:"Verify first",result:"You ask for documents and transaction details. Kunle backs off.",trust:-3,reputation:3,flag:"kunle-verified"},{label:"Block the offer",result:"You keep your money and distance yourself from the deal.",trust:-5,flag:"kunle-blocked"}]},
{id:"aunty-pressure",title:"Family Request",text:"Aunty Bose calls. A family expense has come up and she asks if you can contribute.",person:"Aunty Bose",choices:[{label:"Help with ₦15,000",result:"You contribute. The family appreciates the support.",cash:-15000,trust:8,happiness:5,flag:"family-help"},{label:"Send ₦5,000",result:"You explain your limits and still contribute something.",cash:-5000,trust:4,happiness:2,flag:"family-small-help"},{label:"Explain you can't help",result:"You keep your money and explain your situation honestly.",trust:-2,happiness:-2,flag:"family-no-help"}]}];
const money=(n:number)=>new Intl.NumberFormat("en-NG",{style:"currency",currency:"NGN",maximumFractionDigits:0}).format(n);

export default function Home(){
const[player,setPlayer]=useState<Player|null>(null);const[name,setName]=useState("");const[education,setEducation]=useState("Bachelor's");const[start,setStart]=useState<keyof typeof starts>("Graduate");const[cityName,setCityName]=useState("Lagos");const[log,setLog]=useState<string[]>([]);const[message,setMessage]=useState("");const[story,setStory]=useState<Story|null>(null);const[usedStories,setUsedStories]=useState<string[]>([]);
const begin=()=>{const s=starts[start],city=cities.find(c=>c.name===cityName)||cities[0];setPlayer({name:name.trim()||"Player",education,cash:s.cash,energy:82,happiness:72,day:1,income:s.income,job:s.job,industry:s.industry,home:"Family home",rent:0,food:0,data:0,transport:0,skills:25,reputation:50,relationships:20,business:start==="Entrepreneur"?"Your first venture":null,people:initialPeople,relationship:null,flags:[],city,careerLevel:s.industry==="None"?0:1,careerXp:0});setLog([`You arrived in ${city.name} with a plan.`]);setMessage(`Monday morning in ${city.name}. Your life starts now.`);};
const update=(changes:Partial<Player>,text:string,nextMessage?:string)=>{if(!player)return;const p={...player,...changes,day:player.day+1};setPlayer(p);setLog(l=>[text,...l].slice(0,8));setMessage(nextMessage||"Day "+p.day+". What next?");};
const work=()=>{if(!player)return;if(player.industry==="None")return setMessage("Choose an industry first. Your next job starts your career path.");const ind=industries.find(x=>x.name===player.industry);if(!ind)return;const pay=player.industry==="Entrepreneurship"?Math.max(5000,player.careerLevel*8000):ind.income+(player.careerLevel-1)*7000;const xp=player.careerXp+1;const level=xp>=5?Math.min(5,player.careerLevel+1):player.careerLevel;const newXp=xp>=5?0:xp;update({cash:player.cash+pay,energy:Math.max(0,player.energy-18),happiness:Math.max(0,player.happiness-2),skills:Math.min(100,player.skills+ind.skillGain),careerXp:newXp,careerLevel:level,income:pay},`You worked in ${player.industry} and earned ${money(pay)}. +${ind.skillGain} skill.`,level>player.careerLevel?`Promotion! You reached career level ${level} in ${player.industry}.`:"Keep building your career.");
};
const event=()=>{if(!player)return;const e=events[Math.floor(Math.random()*events.length)];update({cash:Math.max(0,player.cash+e[2]),energy:Math.max(0,Math.min(100,player.energy+e[3])),happiness:Math.max(0,Math.min(100,player.happiness+e[4]))},e[0]+" "+e[1]);};
const storyEvent=()=>{if(!player)return;const available=stories.filter(s=>!usedStories.includes(s.id));if(!available.length){setMessage("You've reached the end of the current story chapter. More stories are coming.");return;}setStory(available[Math.floor(Math.random()*available.length)]);};
const chooseStory=(choice:Choice)=>{if(!player||!story)return;const personIndex=story.person?player.people.findIndex(p=>p.name===story.person):-1;const people=personIndex>=0&&choice.trust!==undefined?player.people.map((p,i)=>i===personIndex?{...p,trust:Math.max(0,Math.min(100,p.trust+(choice.trust||0)))}:p):player.people;const flags=choice.flag?[...player.flags,choice.flag]:player.flags;setPlayer({...player,cash:Math.max(0,player.cash+(choice.cash||0)),energy:Math.max(0,Math.min(100,player.energy+(choice.energy||0))),happiness:Math.max(0,Math.min(100,player.happiness+(choice.happiness||0))),reputation:Math.max(0,Math.min(100,player.reputation+(choice.reputation||0))),skills:Math.max(0,Math.min(100,player.skills+(choice.skills||0))),people,flags,day:player.day+1});setLog(l=>[choice.result,...l].slice(0,8));setMessage(choice.result);setUsedStories(s=>[...s,story.id]);setStory(null);};
const rest=()=>update({cash:Math.max(0,player!.cash-1500),energy:Math.min(100,player!.energy+28),happiness:Math.min(100,player!.happiness+8)},"You stayed home, ate and rested.");
const eat=()=>update({cash:Math.max(0,player!.cash-2500),energy:Math.min(100,player!.energy+14),happiness:Math.min(100,player!.happiness+3),food:player!.food+1},"You bought food and took care of yourself.");
const move=(h:string,r:number)=>{if(!player||player.cash<r*4)return setMessage("You need at least four weeks of rent to move here.");setPlayer({...player,home:h,rent:r,cash:player.cash-r*4});setMessage(`You moved into a ${h}. Four weeks of rent are covered.`);setLog(l=>[`Housing changed to ${h}.`,...l].slice(0,8));};
const changeCity=(city:City)=>{if(!player)return;const fee=Math.round(15000*city.cost);if(player.cash<fee)return setMessage(`Moving to ${city.name} needs ${money(fee)}.`);setPlayer({...player,city,cash:player.cash-fee,energy:Math.max(0,player.energy-10),happiness:Math.min(100,player.happiness+4),rent:0,home:"Family home"});setMessage(`You moved to ${city.name}. ${city.vibe}.`);setLog(l=>[`Relocated to ${city.name}, ${city.state}.`,...l].slice(0,8));};
const chooseIndustry=(ind:Industry)=>{if(!player)return;if(ind.name===player.industry)return setMessage(`You're already building a career in ${ind.name}.`);if(player.cash<ind.entry)return setMessage(`Starting ${ind.name} needs ${money(ind.entry)} for training, tools or entry costs.`);setPlayer({...player,cash:player.cash-ind.entry,industry:ind.name,job:ind.name==="Entrepreneurship"?"Founder":"Entry-level "+ind.name,income:ind.income,careerLevel:1,careerXp:0,skills:Math.min(100,player.skills+3)});setMessage(`You entered ${ind.name}. ${ind.description}`);setLog(l=>[`Career started: ${ind.name}.`,...l].slice(0,8));};
const applyJob=()=>{if(!player)return;if(player.industry==="None")return setMessage("Pick an industry before applying for a career role.");setMessage(`Your current path is ${player.industry}. Work repeatedly to build XP and unlock higher income.`);};
const business=()=>{if(!player)return;if(player.business)return setMessage("You already run a business. Keep growing it.");if(player.cash<50000)return setMessage("You need ₦50,000 to start the first company.");setPlayer({...player,cash:player.cash-50000,business:`${player.city.name} ${player.industry==="Agriculture"?"farm":"small business"}`,reputation:Math.min(100,player.reputation+5)});setMessage(`You started a business in ${player.city.name}.`);setLog(l=>[`You started a business in ${player.city.name}.`,...l].slice(0,8));};
const interact=(i:number,type:"meet"|"help"|"partner")=>{if(!player)return;const person=player.people[i];if(type==="meet"){setPlayer({...player,people:player.people.map((x,k)=>k===i?{...x,friendship:Math.min(100,x.friendship+8),trust:Math.min(100,x.trust+3)}:x),relationships:Math.min(100,player.relationships+4),happiness:Math.min(100,player.happiness+6)});setMessage(`You spent time with ${person.name}. Your relationship is growing.`);setLog(l=>[`You met ${person.name}, your ${person.role}.`,...l].slice(0,8));}else if(type==="help"){if(player.cash<5000)return setMessage("You can't afford to help right now.");setPlayer({...player,cash:player.cash-5000,people:player.people.map((x,k)=>k===i?{...x,trust:Math.min(100,x.trust+14),friendship:Math.min(100,x.friendship+5)}:x),relationships:Math.min(100,player.relationships+5)});setMessage(`You helped ${person.name}. Trust increased.`);setLog(l=>[`You gave ${money(5000)} to ${person.name}.`,...l].slice(0,8));}else{if(person.trust<60)return setMessage(`${person.name} does not trust you enough for a business partnership yet.`);if(player.business)return setMessage("You already have a business.");setPlayer({...player,business:"Partnership business",cash:player.cash+25000,people:player.people.map((x,k)=>k===i?{...x,trust:Math.min(100,x.trust+8)}:x),reputation:Math.min(100,player.reputation+8)});setMessage(`${person.name} joined you as a business partner. You received ₦25,000 in working capital.`);setLog(l=>[`${person.name} became your business partner.`,...l].slice(0,8));}};
const weekly=()=>{if(!player)return;const upkeep=Math.round((player.rent+9000+3500)*player.city.cost);const salary=player.income;const businessIncome=player.business?Math.round(25000/player.city.cost):0;const cash=Math.max(0,player.cash+salary+businessIncome-upkeep);setPlayer({...player,day:1,cash});setLog(l=>[`Week settled in ${player.city.name}: ${money(salary+businessIncome-upkeep)} net cash.`,...l].slice(0,8));setMessage(`A new week begins in ${player.city.name}. Bills are paid.`);};

if(!player)return <main className="shell"><section className="game panel"><div className="eyebrow">OMO • LIFE NO GET MANUAL</div><h1>Start your life.</h1><p className="intro">Choose where you begin. Your city, career and choices shape your story.</p><label>Name<input value={name} onChange={e=>setName(e.target.value)} placeholder="Your name"/></label><label>Education<select value={education} onChange={e=>setEducation(e.target.value)}><option>Secondary</option><option>OND/HND</option><option>Bachelor's</option><option>Master's</option></select></label><label>Starting situation<select value={start} onChange={e=>setStart(e.target.value as keyof typeof starts)}>{Object.keys(starts).map(x=><option key={x}>{x}</option>)}</select></label><label>Starting city<select value={cityName} onChange={e=>setCityName(e.target.value)}>{cities.map(c=><option key={c.name}>{c.name}</option>)}</select></label><button className="primary wide" onClick={begin}>START LIFE →</button></section></main>;

return <main className="shell"><section className="game"><header><div><div className="eyebrow">OMO</div><h1>{player.name}</h1><span className="muted">{player.city.name} • Day {Math.min(player.day,7)} • {player.industry}</span></div><div className="cash">{money(player.cash)}</div></header>
<div className="meters"><div><span>⚡ Energy</span><b>{player.energy}%</b><i><em style={{width:player.energy+"%"}}/></i></div><div><span>❤️ Happiness</span><b>{player.happiness}%</b><i><em style={{width:player.happiness+"%"}}/></i></div></div>
<div className="grid"><div className="stat"><small>🏠 HOME</small><strong>{player.home}</strong></div><div className="stat"><small>🧠 SKILLS</small><strong>{player.skills}%</strong></div><div className="stat"><small>📈 CAREER</small><strong>Lv {player.careerLevel}</strong></div><div className="stat"><small>⭐ REPUTATION</small><strong>{player.reputation}%</strong></div></div>
<div className="message">{message}</div><h3>What will you do?</h3><div className="actions"><button onClick={work}>💼 WORK</button><button onClick={event}>🎲 EVENT</button><button onClick={storyEvent}>📖 STORY</button><button onClick={eat}>🍲 EAT</button><button onClick={rest}>🛏️ REST</button><button onClick={applyJob}>📋 CAREER</button><button onClick={business}>🏢 COMPANY</button><button onClick={()=>setMessage("Open People below to manage relationships.")}>🤝 PEOPLE</button></div>
<details><summary>💼 Industries & careers</summary><p className="muted">Pick a path. Entry costs represent training, tools, certifications or setup. Work builds XP; every 5 work cycles can unlock a new career level.</p>{industries.map(ind=><div className="person" key={ind.name}><div><strong>{ind.icon} {ind.name}</strong><small>{ind.description} • Base {ind.income?money(ind.income):"variable"} • Entry {ind.entry?money(ind.entry):"Free"}</small></div><div className="personActions"><button className="listButton" onClick={()=>chooseIndustry(ind)}>{ind.name===player.industry?"Current":"Choose"}</button></div></div>)}</details>
<details><summary>🌍 Cities</summary><p className="muted">{player.city.work}. Business focus: {player.city.business}.</p>{cities.map(c=><button className="listButton" key={c.name} onClick={()=>changeCity(c)}>{c.name} • {c.state} • move {money(Math.round(15000*c.cost))}</button>)}</details>
<details><summary>🤝 People in your life</summary>{player.people.map((p,i)=><div className="person" key={p.name}><div><strong>{p.name}</strong><small>{p.role} • Trust {p.trust}% • Friendship {p.friendship}%</small></div><div className="personActions"><button className="listButton" onClick={()=>interact(i,"meet")}>Meet</button><button className="listButton" onClick={()=>interact(i,"help")}>Help ₦5k</button><button className="listButton" onClick={()=>interact(i,"partner")}>Partner</button></div></div>)}</details>
<details><summary>📖 Story progress</summary><p className="muted">{usedStories.length} / {stories.length} storylines completed.</p>{stories.map(s=><p key={s.id} className="storyStatus">{usedStories.includes(s.id)?"✓ ":"○ "}{s.title}</p>)}</details>
<details><summary>🏠 Housing</summary>{homes.map(h=><button className="listButton" key={h[0]} onClick={()=>move(h[0],Number(h[1]))}>Move: {h[0]} {h[1]?money(Number(h[1]))+"/week":"Free"}</button>)}</details>
<div className="log"><h3>Life log</h3>{log.map((x,i)=><p key={i}>{x}</p>)}</div>{player.day>7&&<button className="primary wide" onClick={weekly}>SETTLE WEEK & START NEXT →</button>}
{story&&<div className="modal"><div className="storyCard"><div className="eyebrow">LIFE EVENT</div><h2>{story.title}</h2><p>{story.text}</p><div className="storyChoices">{story.choices.map((c,i)=><button key={i} onClick={()=>chooseStory(c)}>{c.label}</button>)}</div></div></div>}
</section></main>;
}